---
title: "Schaum's Chapter 3: Square Matrices"
format: html
author: "Rodolfo León"
date: last-modified
editor: source
editor_options: 
  chunk_output_type: inline
---

```{r}
knitr::opts_knit$set(root.dir = "C:/Users/rodol/OneDrive/Documents/Schaums-mastery/matrices_R", echo = TRUE, warning = FALSE, message = TRUE)
options(stringsAsFactors = FALSE)
```

```{r}
#| echo: false
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggthemes)
  library(Matrix)
  library(MASS)
  library(pander)
})
```

```{r, echo=FALSE}
# Set pander options for table formatting
panderOptions('table.split.table', Inf)   # Avoid splitting tables across pages
panderOptions('table.style', 'multiline') # Enable multiline cell text wrapping
panderOptions('table.alignment.default', 'center') # Align text to the center
panderOptions('table.alignment.rownames', 'left') # Align row names (first column) to the left
panderOptions('table.emphasize.rownames', FALSE)  # Remove the ** from row names
```

```{r}
source("functions/lu_pivot.R")
source("functions/lu_pivot_fr.R")
```


```{r}
# 1. Build the matrices
A <- matrix(c(1, 2, -1,
              3, 8,  9,
              2, -1,  2),
            nrow = 3, byrow = TRUE)
B <- matrix(c(1,2,3,
              4,5,6,
              7,8,9),
            nrow = 3, byrow = TRUE)
C <- matrix(c(2, -1, 4,
              -1, 3, 3,
              -1, 2, 0),
            nrow = 3, byrow = TRUE)
D <- matrix(c(1,0,0,2,
              2,1,0,1,
              0,2,2,0,
              0,3,0,1),
            nrow = 4, byrow = TRUE)
E <- matrix(c(1,2,3,4,
              2,4,-1,1,
              1,-3,4,-4,
              2,2,-3,4),
            nrow = 4, byrow = TRUE)
F <- matrix(c(1,2,3,4,
              2,-2,-1,1,
              1,-3,4,-4,
              2,2,-3,4),
              nrow = 4, byrow = TRUE)
G <- matrix(c(1,2,-2,3,
              -1, 1,0,2,
              3,-3,4,1,
              2,1,1,-2),
            nrow = 4, byrow = TRUE)

```


```{r}
# Call the functions - 'M' for matrix

luM_fr <- lu_pivot_fr(E)
#print_lu_fr(luG_fr)
print_lu_fr(luM_fr, use_pander = TRUE)


luM <- lu_pivot(E)
print_lu(luM)

```

